//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesMiddleware.Monitor.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MesMiddleware.Monitor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 API 連線： 的當地語系化字串。
        /// </summary>
        public static string ApiCard_Connected {
            get {
                return ResourceManager.GetString("ApiCard_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 🌐 Web API 的當地語系化字串。
        /// </summary>
        public static string ApiCard_Title {
            get {
                return ResourceManager.GetString("ApiCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 命令名稱 的當地語系化字串。
        /// </summary>
        public static string Commands_CommandName {
            get {
                return ResourceManager.GetString("Commands_CommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 執行時間 的當地語系化字串。
        /// </summary>
        public static string Commands_ExecutedAt {
            get {
                return ResourceManager.GetString("Commands_ExecutedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重新整理 的當地語系化字串。
        /// </summary>
        public static string Commands_Refresh {
            get {
                return ResourceManager.GetString("Commands_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結果 的當地語系化字串。
        /// </summary>
        public static string Commands_Result {
            get {
                return ResourceManager.GetString("Commands_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態 的當地語系化字串。
        /// </summary>
        public static string Commands_Status {
            get {
                return ResourceManager.GetString("Commands_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已連線 的當地語系化字串。
        /// </summary>
        public static string Common_Connected {
            get {
                return ResourceManager.GetString("Common_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已斷線 的當地語系化字串。
        /// </summary>
        public static string Common_Disconnected {
            get {
                return ResourceManager.GetString("Common_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 錯誤 的當地語系化字串。
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 載入中... 的當地語系化字串。
        /// </summary>
        public static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 N/A 的當地語系化字串。
        /// </summary>
        public static string Common_NA {
            get {
                return ResourceManager.GetString("Common_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 否 的當地語系化字串。
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是 的當地語系化字串。
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清除篩選 的當地語系化字串。
        /// </summary>
        public static string History_ClearFilter {
            get {
                return ResourceManager.GetString("History_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 依追蹤碼篩選... 的當地語系化字串。
        /// </summary>
        public static string History_FilterPlaceholder {
            get {
                return ResourceManager.GetString("History_FilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訊息 的當地語系化字串。
        /// </summary>
        public static string History_Message {
            get {
                return ResourceManager.GetString("History_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重新整理 的當地語系化字串。
        /// </summary>
        public static string History_Refresh {
            get {
                return ResourceManager.GetString("History_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態 的當地語系化字串。
        /// </summary>
        public static string History_Status {
            get {
                return ResourceManager.GetString("History_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態篩選 的當地語系化字串。
        /// </summary>
        public static string History_StatusFilter {
            get {
                return ResourceManager.GetString("History_StatusFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 時間戳記 的當地語系化字串。
        /// </summary>
        public static string History_Timestamp {
            get {
                return ResourceManager.GetString("History_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 追蹤碼 的當地語系化字串。
        /// </summary>
        public static string History_TraceCode {
            get {
                return ResourceManager.GetString("History_TraceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 English 的當地語系化字串。
        /// </summary>
        public static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 简体中文 的當地語系化字串。
        /// </summary>
        public static string Language_SimplifiedChinese {
            get {
                return ResourceManager.GetString("Language_SimplifiedChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 🌐 語言 的當地語系化字串。
        /// </summary>
        public static string Language_Title {
            get {
                return ResourceManager.GetString("Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繁體中文 的當地語系化字串。
        /// </summary>
        public static string Language_TraditionalChinese {
            get {
                return ResourceManager.GetString("Language_TraditionalChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 記憶體活躍： 的當地語系化字串。
        /// </summary>
        public static string MemoryCard_Active {
            get {
                return ResourceManager.GetString("MemoryCard_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 💾 共享記憶體 的當地語系化字串。
        /// </summary>
        public static string MemoryCard_Title {
            get {
                return ResourceManager.GetString("MemoryCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ❌ 失敗： 的當地語系化字串。
        /// </summary>
        public static string Queue_Failed {
            get {
                return ResourceManager.GetString("Queue_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 🕒 最舊排隊時間： 的當地語系化字串。
        /// </summary>
        public static string Queue_OldestQueued {
            get {
                return ResourceManager.GetString("Queue_OldestQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ⏳ 等待中： 的當地語系化字串。
        /// </summary>
        public static string Queue_Pending {
            get {
                return ResourceManager.GetString("Queue_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重新整理 的當地語系化字串。
        /// </summary>
        public static string Queue_Refresh {
            get {
                return ResourceManager.GetString("Queue_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 🔄 重試中： 的當地語系化字串。
        /// </summary>
        public static string Queue_Retrying {
            get {
                return ResourceManager.GetString("Queue_Retrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 佇列狀態概覽 的當地語系化字串。
        /// </summary>
        public static string Queue_Title {
            get {
                return ResourceManager.GetString("Queue_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 📊 總深度： 的當地語系化字串。
        /// </summary>
        public static string Queue_TotalDepth {
            get {
                return ResourceManager.GetString("Queue_TotalDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最後更新： 的當地語系化字串。
        /// </summary>
        public static string ServiceCard_LastUpdate {
            get {
                return ResourceManager.GetString("ServiceCard_LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 服務運行： 的當地語系化字串。
        /// </summary>
        public static string ServiceCard_Running {
            get {
                return ResourceManager.GetString("ServiceCard_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ⚙️ 服務資訊 的當地語系化字串。
        /// </summary>
        public static string ServiceCard_Title {
            get {
                return ResourceManager.GetString("ServiceCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 運行時間： 的當地語系化字串。
        /// </summary>
        public static string ServiceCard_Uptime {
            get {
                return ResourceManager.GetString("ServiceCard_Uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排隊中： 的當地語系化字串。
        /// </summary>
        public static string StatsCard_Queued {
            get {
                return ResourceManager.GetString("StatsCard_Queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已接收： 的當地語系化字串。
        /// </summary>
        public static string StatsCard_Received {
            get {
                return ResourceManager.GetString("StatsCard_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 成功上傳： 的當地語系化字串。
        /// </summary>
        public static string StatsCard_Success {
            get {
                return ResourceManager.GetString("StatsCard_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 📈 統計資訊 的當地語系化字串。
        /// </summary>
        public static string StatsCard_Title {
            get {
                return ResourceManager.GetString("StatsCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最後 Ping： 的當地語系化字串。
        /// </summary>
        public static string StatusCard_LastPing {
            get {
                return ResourceManager.GetString("StatusCard_LastPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 佇列深度： 的當地語系化字串。
        /// </summary>
        public static string StatusCard_QueueDepth {
            get {
                return ResourceManager.GetString("StatusCard_QueueDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態： 的當地語系化字串。
        /// </summary>
        public static string StatusCard_Status {
            get {
                return ResourceManager.GetString("StatusCard_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 📡 連線狀態 的當地語系化字串。
        /// </summary>
        public static string StatusCard_Title {
            get {
                return ResourceManager.GetString("StatusCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 🖥️ 命令記錄 的當地語系化字串。
        /// </summary>
        public static string TabCommands {
            get {
                return ResourceManager.GetString("TabCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 📜 上傳歷史 的當地語系化字串。
        /// </summary>
        public static string TabHistory {
            get {
                return ResourceManager.GetString("TabHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ⏳ 佇列狀態 的當地語系化字串。
        /// </summary>
        public static string TabQueue {
            get {
                return ResourceManager.GetString("TabQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 📊 服務狀態 的當地語系化字串。
        /// </summary>
        public static string TabStatus {
            get {
                return ResourceManager.GetString("TabStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MES 中介軟體監控器 的當地語系化字串。
        /// </summary>
        public static string TrayIconTooltip {
            get {
                return ResourceManager.GetString("TrayIconTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束程式 的當地語系化字串。
        /// </summary>
        public static string TrayMenuExit {
            get {
                return ResourceManager.GetString("TrayMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示監控視窗 的當地語系化字串。
        /// </summary>
        public static string TrayMenuShow {
            get {
                return ResourceManager.GetString("TrayMenuShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MES 中介軟體監控儀表板 的當地語系化字串。
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
